#ifndef __LDARE_GL__
#define __LDARE_GL__

#include "../GL/glcorearb.h"
#include "../GL/wglext.h"

#ifdef DECLARE_GL_POINTER
# define EXTERN
#else
# define EXTERN extern
#endif

extern "C"
{
	// OpenGL function pointers
	EXTERN PFNGLCLEARPROC glClear;
	EXTERN PFNGLCLEARCOLORPROC glClearColor;
	EXTERN PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;
	EXTERN PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB;
	EXTERN PFNGLGENBUFFERSPROC glGenBuffers;
	EXTERN PFNGLBINDBUFFERPROC glBindBuffer;
	EXTERN PFNGLDELETEBUFFERSPROC glDeleteBuffers;
	EXTERN PFNGLBUFFERSUBDATAPROC glBufferSubData;
	EXTERN PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
	EXTERN PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
	EXTERN PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
	EXTERN PFNGLGETERRORPROC glGetError;
	EXTERN PFNGLGETPROGRAMIVPROC glGetProgramiv;
	EXTERN PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
	EXTERN PFNGLGETSHADERIVPROC glGetShaderiv;
	EXTERN PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
	EXTERN PFNGLCREATESHADERPROC glCreateShader;
	EXTERN PFNGLSHADERSOURCEPROC glShaderSource;
	EXTERN PFNGLCOMPILESHADERPROC glCompileShader;
	EXTERN PFNGLCREATEPROGRAMPROC glCreateProgram;
	EXTERN PFNGLATTACHSHADERPROC glAttachShader;
	EXTERN PFNGLLINKPROGRAMPROC glLinkProgram;
	EXTERN PFNGLDELETESHADERPROC glDeleteShader;
	EXTERN PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
	EXTERN PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
	EXTERN PFNGLBUFFERDATAPROC glBufferData;
	EXTERN PFNGLMAPBUFFERPROC glMapBuffer;
	EXTERN PFNGLUNMAPBUFFERPROC glUnmapBuffer;
	EXTERN PFNGLDRAWELEMENTSPROC glDrawElements;
	EXTERN PFNGLUSEPROGRAMPROC glUseProgram;
	EXTERN PFNGLFLUSHPROC glFlush;
	EXTERN PFNGLVIEWPORTPROC glViewport;
}

namespace ldare 
{
	namespace platform
	{
		void* getGlFunctionPointer(const char* glFunctionName);
	}
}
#endif // _LDARE_GL__
