#ifndef _LDARE_COREGL_
#define _LDARE_COREGL_

#include "../GL/glcorearb.h"
#include "../GL/wglext.h"

#ifdef DECLARE_EXTERN_GL
#	define EXTERN extern
#else
#	define EXTERN
#endif

// OpenGL function pointers
EXTERN PFNGLCLEARPROC glClear;
EXTERN PFNGLCLEARCOLORPROC glClearColor;
EXTERN PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;
EXTERN PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB;
EXTERN PFNGLGENBUFFERSPROC glGenBuffers;
EXTERN PFNGLBINDBUFFERPROC glBindBuffer;
EXTERN PFNGLBUFFERDATAPROC glBufferData;
EXTERN PFNGLSHADERSOURCEPROC glShaderSource;
EXTERN PFNGLCOMPILESHADERPROC glCompileShader;
EXTERN PFNGLCREATESHADERPROC glCreateShader;
EXTERN PFNGLATTACHSHADERPROC glAttachShader;
EXTERN PFNGLCREATEPROGRAMPROC glCreateProgram;
EXTERN PFNGLUSEPROGRAMPROC glUseProgram;
EXTERN PFNGLLINKPROGRAMPROC glLinkProgram;
EXTERN PFNGLDELETESHADERPROC glDeleteShader;
EXTERN PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
EXTERN PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
EXTERN PFNGLDRAWARRAYSPROC glDrawArrays;
EXTERN PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
EXTERN PFNGLGETSHADERIVPROC glGetShaderiv;
EXTERN PFNGLGETPROGRAMIVPROC glGetProgramiv;
EXTERN PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
EXTERN PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
EXTERN PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
#endif // _LDARE_COREGL_

